#!/bin/sh -l
. $HOME/.bashrc
. ${DIR_UTIL}/descr_CPS.sh

set -eu

stlist="02 05 08 11"
ylist=`seq 2002 2021`
if [[ $# -eq 1 ]]
then
   stlist=$1
fi
if [[ $# -eq 2 ]]
then
   stlist=$1
   ylist=$2
fi
for st in $stlist
do
   for yyyy in $ylist
   do
      n_IC_local=`ls $IC_CLM_CPS_DIR/$st/*$yyyy-${st}*.nc 2>/dev/null|wc -l`
      if [[ $n_IC_local -eq 50 ]]
      then
          echo "$yyyy$st ready"
      else
          echo "$yyyy$st incomplete" $n_IC_local
      fi
   done
   echo ""
   read -p "Press enter to continue"
done
