#!/bin/sh -l
. $HOME/.bashrc
. ${DIR_UTIL}/descr_CPS.sh

set -eu

echo "enter the month to check (leave empty if you want all months)"
read st
echo ""
if [[ -z $st ]]
then
    echo "checking all st"
    str_st="all st"
    stlist="02 05 08 11"
else    
    echo "checking start-date $st"
    str_st=$st
    stlist=$st
fi

ylist=`seq 2002 2021`
for st in $stlist
do
   n_st_done=0
   echo "$st hindcast done"
   for yyyy in $ylist
   do
      n_done_juno=`ls $DIR_CASES/${SPSSystem}_${yyyy}${st}_0??/logs/run_moredays_*DONE 2>/dev/null|wc -l`
         if [[ $(($n_done_juno)) -lt 25 ]]
         then
             list2do=""
             for i in {01..25}
             do
                export caso=${SPSSystem}_${yyyy}${st}_0${i}
set +eu
                . ~/load_miniconda; conda activate env_tools
set -eu
                n_done_csv=`python $DIR_CPS/csv_reader.py`
                conda deactivate

                if [[ $n_done_csv -eq 1 ]]
                then
                   n_done_juno=$(($n_done_juno + 1))
                   continue
                fi
                hinddone_juno=`ls $DIR_CASES/${SPSSystem}_${yyyy}${st}_0${i}/logs/run_moredays_*DONE 2>/dev/null|wc -l`
                if [[ $hinddone_juno -eq 0 ]]
                then
                    list2do+=" ${SPSSystem}_${yyyy}${st}_0${i}"
                    if [[ `echo $list2do|wc -w` -eq $((25 - $n_done_juno)) ]]
                    then
                       break
                    fi
                fi
             done
             if [[ $n_done_juno -gt 0 ]]
             then
                if [[ $n_done_juno -eq 25 ]]
                then
                   echo "$yyyy$st COMPLETE"
                elif [[ $n_done_juno -eq 0 ]]
                then
                   echo "$yyyy$st NONE MEMBER COMPLETED"
                else
                   echo "$yyyy$st done number $n_done_juno"
                   echo "members still to be run: $list2do"
                fi
             fi
         else
            echo "$yyyy$st COMPLETE"
         fi
  
      n_st_done=$(($n_st_done + $n_done_juno))
   done
   echo "TOTAL NUMBER DONE FOR START-DATE $st: $n_st_done"
   echo "Percentage                          : $(($n_st_done * 100 / $((25 * 20))))%"
   echo ""
   read -p "Press enter to continue"
done
