#!/bin/sh -l
. $HOME/.bashrc
. ${DIR_UTIL}/descr_CPS.sh

set -eu

for st in `seq -w 1 12`
do
   n_rsync=0
   for yyyy in {1993..2022}
   do
      n_IC_local=`ls $IC_NEMO_CPS_DIR/$st/*$yyyy-${st}*.nc 2>/dev/null|wc -l`
      n_IC_CICE_local=`ls $IC_CICE_CPS_DIR/$st/*$yyyy-${st}*.nc 2>/dev/null|wc -l`
      if [[ $n_IC_local -eq 4 ]] && [[ $n_IC_CICE_local -eq 4 ]]
      then
          echo "$yyyy$st ready"
      else
          echo "$yyyy$st incomplete NEMO" $n_IC_local " CICE " $n_IC_CICE_local
      fi
   done
   echo ""
   read -p "Press enter to continue"
done
