#!/bin/sh -l
. $HOME/.bashrc
. ${DIR_UTIL}/descr_CPS.sh

set -eu

echo "enter the month to check (leave empty if you want all months)"
read st
echo ""
if [[ -z $st ]]
then
    echo "checking all st"
    str_st="all st"
    stlist=`seq -w 1 12`
else    
    echo "checking start-date $st"
    str_st=$st
    stlist=$st
fi

ylist=`seq 1993 2022`
for st in $stlist
do
   n_st_done=0
   echo "$st hindcast done"
   for yyyy in $ylist
   do
      n_done=`ls $DIR_ARCHIVE1/${SPSSystem}_${yyyy}${st}_0??.transfer_from_*_DONE 2>/dev/null|wc -l`
      n_done_juno=`ls $DIR_CASES1/${SPSSystem}_${yyyy}${st}_0??/logs/*6months_done 2>/dev/null|wc -l`
      if [[ $(($n_done + $n_done_juno)) -ne 0 ]]
      then
          echo "$yyyy$st done number $(($n_done + $n_done_juno))"
      fi
      n_st_done=$(($n_st_done + $n_done + $n_done_juno))
   done
   echo "TOTAL NUMBER DONE FOR START-DATE $st: $n_st_done"
   echo "Percentage                          : $(($n_st_done * 100 / $((30 * 30))))%"
   echo ""
   read -p "Press enter to continue"
done
