#!/bin/sh -l
. $HOME/.bashrc
. ${DIR_UTIL}/descr_CPS.sh

set -eu

stlist=`seq -w 1 12`
ylist=`seq 1993 2022`
if [[ $# -eq 1 ]]
then
   stlist=$1
fi
if [[ $# -eq 2 ]]
then
   stlist=$1
   ylist=$2
fi
for st in $stlist
do
   for yyyy in $ylist
   do
      n_IC_local=`ls $IC_NEMO_CPS_DIR/$st/*$yyyy-${st}*.nc 2>/dev/null|wc -l`
      n_IC_CICE_local=`ls $IC_CICE_CPS_DIR/$st/*$yyyy-${st}*.nc 2>/dev/null|wc -l`
      if [[ $n_IC_local -eq 4 ]] && [[ $n_IC_CICE_local -eq 4 ]]
      then
          echo "$yyyy$st ready"
      else
          echo "$yyyy$st incomplete NEMO" $n_IC_local " CICE " $n_IC_CICE_local
      fi
   done
   echo ""
   read -p "Press enter to continue"
done
