#!/bin/sh -l
. ~/.bashrc
. ${DIR_UTIL}/descr_CPS.sh
if [[ "${machine}" == "zeus" ]] ; then
   source /usr/share/Modules/init/sh
   module load intel19.5/19.5.281
   module load intel19.5/netcdf/C_4.7.2-F_4.5.2_CXX_4.3.1
   module load intel19.5/udunits/2.2.26
   module load intel19.5/hdf5/1.10.5
   module load intel19.5/szip/2.1.1
   module load curl/7.66.0
   module load impi19.5/esmf/7.1.0-intelmpi-64-O
   module load intel19.5/nco/4.8.1
   export compress='ncks -O -L 4 -4 --no_abc'
   export compressC3S='ncks -Oh -L 4 -7 --no_abc'
# to decompress/uncompress ncks -O -6
elif [[ "${machine}" == "cassandra" ]] ; then 
  . $DIR_UTIL/condaactivation.sh
  condafunction activate env_tools  
  
elif [[ "${machine}" == "juno" ]] ; then 
  module load intel-2021.6.0/nco/5.0.6-jp6y4
 
elif [[ "${machine}" == "leonardo" ]] ; then 
  . $DIR_UTIL/condaactivation.sh
  condafunction activate env_tools


  export MANPATH="/usr/local/share/man"


  check_modul=`which ncks |grep ncks |wc -l`
  echo "NCO CORRECTLY LOADED (should echo 1) " $check_modul
  if [[ $check_modul -eq 0 ]] ; then
     echo "problems in loading nco modules"
     exit 1
  fi 
fi 
# to decompress/uncompress ncks -O -6
export compress='ncks -O -L 4 -4 --no_abc'
export compressC3S='ncks -Oh -L 4 -7 --no_abc'

