#!/bin/sh -l
. ~/.bashrc
. $DIR_UTIL/descr_CPS.sh
if [[ $machine == "juno" ]]
then
   module load intel-2021.6.0/ncl/6.6.2-p2sqo
   export NCARG_COLORMAPS=$HOME/ncl/colormaps:$NCARG_ROOT/lib/ncarg/colormaps
elif [[ $machine == "leonardo" ]]
then
    . $DIR_UTIL/condaactivation.sh
    condafunction deactivate $envcondacm3
    condafunction activate env_tools
    export NCARG_COLORMAPS=$HOME/ncl/colormaps:$NCARG_ROOT/lib/ncarg/colormaps
else
   :
fi
