#!/bin/sh -l

. ~/.bashrc
. $DIR_UTIL/descr_CPS.sh
set -euvx

if [[ $machine == "juno" ]]
then
   echo "test"
   module load intel-2021.6.0/imagemagick/7.0.8-7-2475g
elif [[ $machine == "leonardo" ]]
then
     . $DIR_UTIL/condaactivation.sh
     condafunction activate image_convert
fi

