#!/bin/sh -l
. ~/.bashrc
. ${DIR_UTIL}/descr_CPS.sh

if [[ $machine == "zeus" ]]
then
   source /usr/share/Modules/init/sh
   module load intel19.5/magics/3.3.1
   module load intel19.5/19.5.281
   module load intel19.5/proj/6.2.1
   module load intel19.5/udunits/2.2.26
   module load intel19.5/szip/2.1.1
   module load intel19.5/netcdf-threadsafe/C_4.7.2-F_4.5.2_CXX_4.3.1
   module load intel19.5/hdf5-threadsafe/1.10.5
   module load intel19.5/eccodes/2.12.5
   module load intel19.5/cdo/1.9.8
elif [[ $machine == "juno" ]]
then
   module load intel-2021.6.0/cdo-threadsafe/2.1.1-lyjsw
elif [[ "${machine}" == "marconi" ]] ; then 
   export MANPATH="/usr/local/share/man"
   source /etc/profile.d/modules.sh
   module purge
   module purge
   module load zlib/1.2.8--gnu--6.1.0
   module load szip/2.1--gnu--6.1.0
   module load intel/pe-xe-2018--binary
   module load hdf5/1.10.4--intel--pe-xe-2018--binary
   module load netcdf/4.6.1--intel--pe-xe-2018--binary
   module load profile/advanced
  # ncl (need netcdf before and hdf5,szip,zlib,intel)
  module load udunits/2.2.28--intel--pe-xe-2018--binary
  module load ncl/6.6.2--intel--pe-xe-2018--binary
  module load mkl/2018--binary

  module load eccodes/2.13.0

  module load nco/4.8.1
  module load cdo/1.9.7
  export MANPATH="/usr/local/share/man"
  export NCARG_ROOT=/cineca/prod/opt/libraries/ncl/6.6.2/intel--pe-xe-2018--binary
  export NCARG_COLORMAPS=$NCARG_ROOT/lib/ncarg/colormaps:$HOME/ncl_colormaps


  check_modul=`which cdo |grep cdo |wc -l`
  echo $check_modul
  if [[ $check_modul -eq 0 ]] ; then
     echo "problems in loading cdo modules"
     exit 1
  fi
elif [[ "${machine}" == "leonardo" ]]  || [[ "${machine}" == "cassandra" ]]; then
    . $DIR_UTIL/condaactivation.sh
    condafunction activate env_tools
fi
