if (MPILIB STREQUAL impi)
  string(APPEND FFLAGS " -qmkl=cluster -qopt-zmm-usage=high -no-fma  -march=native ")
  string(APPEND CFLAGS " -qmkl=cluster -qopt-zmm-usage=high -no-fma  -march=native ")
  string(APPEND CXXFLAGS " -qmkl=cluster -qopt-zmm-usage=high -no-fma  -march=native ")
  string(APPEND LDFLAGS " -L/leonardo/pub/usera07cmc/a07cmc00/spack-0.21.0-05/install/linux-rhel8-icelake/oneapi-2023.2.0/xerces-c-3.2.4-fy6ksf635ybje53u65jqeyncj2djeeyu/lib/ -lxerces-c ")
endif()
set(AR "xiar")
set(ARFLAGS "cru")
set(MPICC "mpiicc")
set(MPICXX "mpiicpc")
set(MPIFC "mpiifort")

